/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skripsi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Ulil_Mz
 */
public class form_petugas extends javax.swing.JDialog {

    private static Connection con;

    /**
     * Creates new form form_petugas
     */
    public form_petugas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            con = koneksidb.getConnection();
            System.out.println("Koneksi Sukses");
        } catch (Exception e) {
        }
        setLocationRelativeTo(null);

        autokode();

    }

    public void bersih() {
        u_idpetugas.setText(null);
        u_nama.setText(null);
        u_passwort.setText(null);
        u_alamat.setText(null);
        u_jabatan.setText(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        u_idpetugas = new javax.swing.JTextField();
        u_nama = new javax.swing.JTextField();
        u_passwort = new javax.swing.JPasswordField();
        u_jabatan = new javax.swing.JTextField();
        u_bttambah = new javax.swing.JButton();
        u_btedit = new javax.swing.JButton();
        u_bthapus = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        u_alamat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel1.setText("Id. Petugas");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel3.setText("Password");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel4.setText("Jabatan");

        u_bttambah.setText("SIMPAN");
        u_bttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_bttambahActionPerformed(evt);
            }
        });

        u_btedit.setText("EDIT");
        u_btedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_bteditActionPerformed(evt);
            }
        });

        u_bthapus.setText("HAPUS");
        u_bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_bthapusActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel5.setText("Alamat");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(u_bttambah)
                .addGap(18, 18, 18)
                .addComponent(u_btedit, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(u_bthapus)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(u_idpetugas)
                    .addComponent(u_nama)
                    .addComponent(u_passwort)
                    .addComponent(u_jabatan, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(u_alamat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(u_idpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(u_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(u_passwort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(u_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(u_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u_bttambah)
                    .addComponent(u_btedit)
                    .addComponent(u_bthapus))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        setBounds(0, 0, 322, 380);
    }// </editor-fold>//GEN-END:initComponents

    private void u_bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_bttambahActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "insert into petugas values(?,?,?,?,?)";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql:///skripsi", "root", "");
            PreparedStatement UR = con.prepareStatement(sql);
            UR.setString(1, u_idpetugas.getText());
            UR.setString(2, u_nama.getText());
            UR.setString(3, u_passwort.getText());
            UR.setString(4, u_alamat.getText());
            UR.setString(5, u_jabatan.getText());
            UR.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Tersimpan");
            bersih();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        autokode();
    }//GEN-LAST:event_u_bttambahActionPerformed

    private void u_bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_bthapusActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "Delete from petugas where kode_petugas=?";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql:///skripsi", "root", "");
            PreparedStatement pen = con.prepareStatement(sql);
            pen.setString(1, u_idpetugas.getText());
            pen.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Berhasil Di Hapus ");
            bersih();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_u_bthapusActionPerformed

    private void u_bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_bteditActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "update petugas set nama=?, Password=?, alamat=?, jabatan=? where kode_petugas=?";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql:///skripsi", "root", "");
            PreparedStatement update = con.prepareStatement(sql);
            update.setString(1, u_idpetugas.getText());
            update.setString(2, u_nama.getText());
            update.setString(3, u_passwort.getText());
            update.setString(4, u_alamat.getText());
            update.setString(5, u_jabatan.getText());
            update.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Sudah Di Edit");
            bersih();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_u_bteditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                form_petugas dialog = new form_petugas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void autokode() {
        try {

            String query = "SELECT MAX(right(no_pendaftar,5))AS no FROM pdb";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                if (rs.first() == false) {
                    u_idpetugas.setText("01");
                } else {
                    rs.last();
                    int auto_id = rs.getInt(1) + 1;
                    String no = String.valueOf(auto_id);
                    int nolong = no.length();
                    for (int a = 0; a < 6 - nolong; a++) {
                        no = "0" + no;
                    }

                    u_idpetugas.setText(no);
                }
            }
            rs.close();
            st.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR:\n" + e.toString(), "kesalahan", JOptionPane.WARNING_MESSAGE);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField u_alamat;
    private javax.swing.JButton u_btedit;
    private javax.swing.JButton u_bthapus;
    private javax.swing.JButton u_bttambah;
    private javax.swing.JTextField u_idpetugas;
    private javax.swing.JTextField u_jabatan;
    private javax.swing.JTextField u_nama;
    private javax.swing.JPasswordField u_passwort;
    // End of variables declaration//GEN-END:variables
}
