/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skripsi;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Ulil_Mz
 */
public class form_pentashih extends javax.swing.JDialog {
      private static Connection con; 
    /**
     * Creates new form form_pentashih
     */
    public form_pentashih(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        autokode3();
    }
    
     private void autokode3() {
        try {

            String query = "SELECT MAX(right(no_induk,5))AS no FROM peserta_tahfidz";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                if (rs.first() == false) {
                    e_idpentashih.setText("0001");
                } else {
                    rs.last();
                    int auto_id = rs.getInt(1) + 1;
                    String no = String.valueOf(auto_id);
                    int nolong = no.length();
                    for (int a = 0; a < 1 - nolong; a++) {
                        no = "000" + no;
                    }
                   e_idpentashih.setText("000" + no);
                }
            }
            rs.close();
            st.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR:\n" + e.toString(), "kesalahan", JOptionPane.WARNING_MESSAGE);
        }
    }
     
      public void bersih() {
        e_idpentashih.setText(null);
        e_nama.setText(null);
        e_tempat.setText(null);
        e_tanggal.setDate(null);
        e_alamat.setText(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        e_idpentashih = new javax.swing.JTextField();
        e_nama = new javax.swing.JTextField();
        e_tempat = new javax.swing.JTextField();
        e_tanggal = new com.toedter.calendar.JDateChooser();
        e_alamat = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        e_bttambah = new javax.swing.JButton();
        e_btedit = new javax.swing.JButton();
        e_bthapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Id Pentashih");

        jLabel2.setText("Nama");

        jLabel3.setText("Tempat dan Tanggal Lahir");

        jLabel4.setText("Alamat");

        e_bttambah.setText("TAMBAH");
        e_bttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_bttambahActionPerformed(evt);
            }
        });

        e_btedit.setText("EDIT");
        e_btedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_bteditActionPerformed(evt);
            }
        });

        e_bthapus.setText("HAPUS");
        e_bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_bthapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(e_bttambah)
                        .addGap(18, 18, 18)
                        .addComponent(e_btedit, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(e_bthapus)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(e_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(e_idpentashih, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(e_tempat, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(e_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(e_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(e_idpentashih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(e_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(e_tempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(e_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(e_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_bttambah)
                    .addComponent(e_btedit)
                    .addComponent(e_bthapus))
                .addContainerGap(209, Short.MAX_VALUE))
        );

        setBounds(0, 0, 406, 529);
    }// </editor-fold>//GEN-END:initComponents

    private void e_bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_bttambahActionPerformed
        // TODO add your handling code here:
         if ((e_idpentashih.getText().equals(""))) {
            JOptionPane.showMessageDialog(this, "Isi Data dengan Lengkap!");
        } else {
            try {
              
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String Tanggal = String.valueOf(sdf.format(e_tanggal.getDate()));

                String sql = "insert into pdb values (?,?,?,?,?)";
                Class.forName("com.mysql.jdbc.Driver");
                Connection koneksi = DriverManager.getConnection("jdbc:mysql:///skripsi", "root", "");
                PreparedStatement tulis = koneksi.prepareStatement(sql);
                tulis.setString(1, e_idpentashih.getText());
                tulis.setString(2, e_nama.getText());
                tulis.setString(3, e_tempat.getText());
                tulis.setString(4, Tanggal);
                tulis.setString(5, e_alamat.getText());
                tulis.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Berhasil Di Simpan");
                bersih();
                autokode3();
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, ex);
                //Logger.getLogger(form_datatahfidz.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);
                //Logger.getLogger(form_datatahfidz.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_e_bttambahActionPerformed

    private void e_bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_bteditActionPerformed
        // TODO add your handling code here:
          if ((e_idpentashih.getText().equals(""))) {
            JOptionPane.showMessageDialog(this, "Isi Data dengan Lengkap!");
        } else {
            try {
              
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String Tanggal = String.valueOf(sdf.format(e_tanggal.getDate()));

                String sql = "UPDATE pentashih SET nama=?,tempat=?,"
                        + "tanggal_lahir=?,alamat=? WHERE id_pentashih=?";
                Class.forName("com.mysql.jdbc.Driver");
                Connection koneksi = DriverManager.getConnection("jdbc:mysql:///skripsi", "root", "");
                PreparedStatement tulis = koneksi.prepareStatement(sql);
                tulis.setString(1, e_idpentashih.getText());
                tulis.setString(2, e_nama.getText());
                tulis.setString(3, e_tempat.getText());
                tulis.setString(4, Tanggal);
                tulis.setString(5, e_alamat.getText());
                tulis.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Berhasil Di Simpan");
                bersih();
                autokode3();
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, ex);
                //Logger.getLogger(form_datatahfidz.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);
                //Logger.getLogger(form_datatahfidz.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_e_bteditActionPerformed

    private void e_bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_bthapusActionPerformed
        // TODO add your handling code here:
           try {
            String sql = "Delete from pentashih where no_pendaftar=?";
            Class.forName("com.mysql.jdbc.Driver");
            Connection koneksi = DriverManager.getConnection("jdbc:mysql:///skripsi", "root", "");
            PreparedStatement tulis = koneksi.prepareStatement(sql);
            tulis.setString(1, e_idpentashih.getText());
            tulis.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Berhasil Di Hapus ");
            bersih();
             autokode3();
        } catch (ClassNotFoundException | SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_e_bthapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_pentashih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_pentashih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_pentashih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_pentashih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                form_pentashih dialog = new form_pentashih(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField e_alamat;
    private javax.swing.JButton e_btedit;
    private javax.swing.JButton e_bthapus;
    private javax.swing.JButton e_bttambah;
    private javax.swing.JTextField e_idpentashih;
    private javax.swing.JTextField e_nama;
    private com.toedter.calendar.JDateChooser e_tanggal;
    private javax.swing.JTextField e_tempat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
