/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skripsi;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Ulil_Mz
 */
public class form_data_pdb extends javax.swing.JDialog {

    private Object kon;
    private static Connection con;
    private Object konek;

    /**
     * Creates new form form_data_pdb
     */
    public form_data_pdb(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        try {
            con = koneksidb.getConnection();
            System.out.println("Koneksi Sukses");
        } catch (Exception e) {
        }

        autokode();
        p_cbpendidikan.setSelectedItem(null);
        p_cbmasukL.setSelectedItem(null);
        p_cbanakke.setSelectedItem(null);
        p_cbdarike.setSelectedItem(null);
        p_cbstatus.setSelectedItem(null);
        p_cbpenghasilan.setSelectedItem(null);
        p_penayah.setSelectedItem(null);
        p_pendibu.setSelectedItem(null);
        setLocationRelativeTo(null);
        p_pendaftaran.setEnabled(false);
        p_edit.setEnabled(false);
        p_hapus.setEnabled(false);

    }

    form_data_pdb() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        p_pendaftaran = new javax.swing.JTextField();
        p_nama = new javax.swing.JTextField();
        p_tempat = new javax.swing.JTextField();
        p_cbpendidikan = new javax.swing.JComboBox();
        p_cbmasukL = new javax.swing.JComboBox();
        p_cbanakke = new javax.swing.JComboBox();
        p_cbdarike = new javax.swing.JComboBox();
        p_cbstatus = new javax.swing.JComboBox();
        p_nayah = new javax.swing.JTextField();
        p_nibu = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        p_nope = new javax.swing.JTextField();
        p_date = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        p_alamat = new javax.swing.JTextField();
        p_cbpenghasilan = new javax.swing.JComboBox();
        p_simpan = new javax.swing.JButton();
        p_edit = new javax.swing.JButton();
        p_hapus = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        p_cbadmin = new javax.swing.JCheckBox();
        p_cbfoto = new javax.swing.JCheckBox();
        p_cbijazah = new javax.swing.JCheckBox();
        p_penayah = new javax.swing.JComboBox();
        p_pendibu = new javax.swing.JComboBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        p_bersih = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel1.setText("No. Pendaftaran");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 42, 86, 16);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel2.setText("Nama Lengkap");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 86, 79, 16);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel3.setText("Jenis Kelamin");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 125, 73, 16);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel4.setText("Tempat /Tgl.Lahir");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 168, 95, 16);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel5.setText("Pendidikan Terakhir");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 206, 106, 16);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel6.setText("Masuk Lembaga");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 249, 88, 16);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel7.setText("Anak Ke");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 287, 47, 16);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel8.setText("dari");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(206, 287, 20, 16);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel9.setText("Saudara");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(277, 287, 43, 16);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel10.setText("Status Anak");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 325, 66, 16);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel11.setText("Nama Ayah");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(371, 36, 63, 16);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel12.setText("Nama Ibu");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(371, 74, 51, 16);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel13.setText("Penghasilan Orang Tua");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(371, 204, 125, 16);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel14.setText("pendidikan Ayah");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(371, 242, 92, 16);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel15.setText("Pendidikan Ibu");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(370, 280, 80, 16);

        p_pendaftaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                p_pendaftaranKeyPressed(evt);
            }
        });
        getContentPane().add(p_pendaftaran);
        p_pendaftaran.setBounds(146, 40, 95, 30);
        getContentPane().add(p_nama);
        p_nama.setBounds(146, 84, 136, 30);
        getContentPane().add(p_tempat);
        p_tempat.setBounds(146, 166, 71, 30);

        p_cbpendidikan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SD/MI", "SLTP/MTs" }));
        p_cbpendidikan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                p_cbpendidikanItemStateChanged(evt);
            }
        });
        getContentPane().add(p_cbpendidikan);
        p_cbpendidikan.setBounds(146, 204, 79, 30);

        p_cbmasukL.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MTs NJ", "MTsN", "SMPNJ", "MANJ", "MAN", "SMANJ", "SMKNJ", " ", " " }));
        getContentPane().add(p_cbmasukL);
        p_cbmasukL.setBounds(146, 247, 79, 30);

        p_cbanakke.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        getContentPane().add(p_cbanakke);
        p_cbanakke.setBounds(146, 285, 50, 30);

        p_cbdarike.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        getContentPane().add(p_cbdarike);
        p_cbdarike.setBounds(236, 285, 40, 30);

        p_cbstatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sulung", "Tengah", "Bungsu", " " }));
        getContentPane().add(p_cbstatus);
        p_cbstatus.setBounds(146, 323, 90, 30);
        getContentPane().add(p_nayah);
        p_nayah.setBounds(524, 34, 127, 30);
        getContentPane().add(p_nibu);
        p_nibu.setBounds(524, 72, 127, 30);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel20.setText("No Hp");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(370, 320, 35, 16);
        getContentPane().add(p_nope);
        p_nope.setBounds(520, 320, 129, 30);
        getContentPane().add(p_date);
        p_date.setBounds(223, 166, 123, 30);

        jLabel21.setText("Alamat Lengkap ");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(371, 110, 95, 16);
        getContentPane().add(p_alamat);
        p_alamat.setBounds(524, 110, 161, 76);

        p_cbpenghasilan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "kurang lebih 1.000.000", "1.000.000", "kurang lebih 2.000.000", "2.000.000", "Lebih  2.000.000", " ", " " }));
        getContentPane().add(p_cbpenghasilan);
        p_cbpenghasilan.setBounds(524, 204, 161, 30);

        p_simpan.setText("SIMPAN");
        p_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_simpanActionPerformed(evt);
            }
        });
        getContentPane().add(p_simpan);
        p_simpan.setBounds(170, 420, 80, 31);

        p_edit.setText("EDIT");
        p_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_editActionPerformed(evt);
            }
        });
        getContentPane().add(p_edit);
        p_edit.setBounds(270, 420, 69, 31);

        p_hapus.setText("HAPUS");
        p_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(p_hapus);
        p_hapus.setBounds(370, 420, 73, 31);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel22.setText("Persyaratan:");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(370, 360, 66, 16);

        p_cbadmin.setText("Administrasi");
        getContentPane().add(p_cbadmin);
        p_cbadmin.setBounds(520, 360, 110, 24);

        p_cbfoto.setText("Foto 3 X 4");
        getContentPane().add(p_cbfoto);
        p_cbfoto.setBounds(520, 380, 110, 24);

        p_cbijazah.setText("Foto Copy Ijazah");
        getContentPane().add(p_cbijazah);
        p_cbijazah.setBounds(520, 400, 110, 24);

        p_penayah.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SD/MI", "SLTP/MTs", "SLTA/MA", "SI/DiPLOMA" }));
        getContentPane().add(p_penayah);
        p_penayah.setBounds(524, 242, 129, 30);

        p_pendibu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SD/MI", "SLTP/MTs", "SLTA/MA", "SI/DiPLOMA" }));
        getContentPane().add(p_pendibu);
        p_pendibu.setBounds(520, 280, 129, 30);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Laki-Laki");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(146, 122, 84, 28);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Perempuan");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(230, 120, 90, 28);

        p_bersih.setText("Bersih");
        p_bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_bersihActionPerformed(evt);
            }
        });
        getContentPane().add(p_bersih);
        p_bersih.setBounds(70, 420, 67, 32);

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 40, 53, 32);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/latar1.jpg"))); // NOI18N
        jLabel16.setText("jLabel16");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(0, 0, 740, 470);

        setBounds(0, 0, 758, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void p_cbpendidikanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_p_cbpendidikanItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_p_cbpendidikanItemStateChanged
    public void bersih() {
        p_pendaftaran.setText(null);
        p_nama.setText(null);
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        p_tempat.setText(null);
        p_date.setDate(null);
        p_cbpendidikan.setSelectedItem(null);
        p_cbmasukL.setSelectedItem(null);
        p_cbanakke.setSelectedItem(null);
        p_cbdarike.setSelectedItem(null);
        p_cbstatus.setSelectedItem(null);
        p_nayah.setText(null);
        p_nibu.setText(null);
        p_alamat.setText(null);
        p_cbpenghasilan.setSelectedItem(null);
        p_penayah.setSelectedItem(null);
        p_pendibu.setSelectedItem(null);
        p_nope.setText(null);
        p_cbadmin.setSelected(false);
        p_cbfoto.setSelected(false);
        p_cbijazah.setSelected(false);
        p_pendaftaran.setEnabled(false);
        p_edit.setEnabled(false);
        p_hapus.setEnabled(false);
        p_simpan.setEnabled(true);

    }

    private void p_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_simpanActionPerformed
        // TODO add your handling code here:
        String JenKel, adminis, ft, ij;
        if (jRadioButton1.isSelected()) {
            JenKel = "Laki-Laki";
        } else {
            JenKel = "Perempuan";
        }
        if ((p_pendaftaran.getText().equals("")) || (p_nama.getText().equals("")) || (JenKel.equals(""))
                || (p_tempat.getText().equals("")) || (p_nayah.getText().equals("")) || (p_nibu.getText().equals(""))
                || (p_alamat.getText().equals("")) || (p_nope.getText().equals("")) || ((!jRadioButton1.isSelected() && !jRadioButton2.isSelected()))) {
            JOptionPane.showMessageDialog(this, "Isi Data dengan Lengkap!");
        } else {
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String Tanggal = String.valueOf(sdf.format(p_date.getDate()));
                //String JenKel;
                if (jRadioButton1.isSelected()) {
                    JenKel = "Laki-Laki";
                } else {
                    JenKel = "Perempuan";
                }

                if (p_cbadmin.isSelected()) {
                    adminis = "Ada";

                } else {
                    adminis = "Belum";
                }

                if (p_cbfoto.isSelected()) {
                    ft = "Ada";

                } else {
                    ft = "Belum";
                }
                if (p_cbijazah.isSelected()) {
                    ij = "Ada";

                } else {
                    ij = "Belum";
                }
                String sql = "insert into pdb values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                Class.forName("com.mysql.jdbc.Driver");
                Connection koneksi = DriverManager.getConnection("jdbc:mysql:///skripsi", "root", "");
                PreparedStatement tulis = koneksi.prepareStatement(sql);
                tulis.setString(1, p_pendaftaran.getText());
                tulis.setString(2, p_nama.getText());
                tulis.setString(3, JenKel);
                tulis.setString(4, p_tempat.getText());
                tulis.setString(5, Tanggal);
                tulis.setString(6, p_cbpendidikan.getSelectedItem().toString());
                tulis.setString(7, p_cbmasukL.getSelectedItem().toString());
                tulis.setString(8, p_cbanakke.getSelectedItem().toString());
                tulis.setString(9, p_cbdarike.getSelectedItem().toString());
                tulis.setString(10, p_cbstatus.getSelectedItem().toString());
                tulis.setString(11, p_nayah.getText());
                tulis.setString(12, p_nibu.getText());
                tulis.setString(13, p_alamat.getText());
                tulis.setString(14, p_cbpenghasilan.getSelectedItem().toString());
                tulis.setString(15, p_penayah.getSelectedItem().toString());
                tulis.setString(16, p_pendibu.getSelectedItem().toString());
                tulis.setString(17, p_nope.getText());
                tulis.setString(18, adminis);
                tulis.setString(19, ft);
                tulis.setString(20, ij);
                tulis.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Berhasil Di Simpan");
                bersih();

                //Tampil_Tabel();
            } catch (ClassNotFoundException | SQLException | HeadlessException e) {
            }

            autokode();
            //p_nama.requestFocus();
        }
    }//GEN-LAST:event_p_simpanActionPerformed

    private void p_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_editActionPerformed
        // TODO add your handling code here:
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String Tanggal = String.valueOf(sdf.format(p_date.getDate()));
            String JenKel, adminis, ft, ij;
            if (jRadioButton1.getText().equalsIgnoreCase("laki-Laki")) {
                JenKel = "Laki-Laki";
            } else {
                JenKel = "Perempuan";
            }
            if (p_cbadmin.isSelected()) {
                adminis = "Ada";

            } else {
                adminis = "Belum";
            }

            if (p_cbfoto.isSelected()) {
                ft = "Ada";

            } else {
                ft = "Belum";
            }
            if (p_cbijazah.isSelected()) {
                ij = "Ada";

            } else {
                ij = "Belum";
            }
            String sql = "Update pdb Set nama=?, jenkel=?,tempat_lahir=?, tanggal_lahir=?, "
                    + "pendidikan=?, masuk_lembaga=?, anak_ke=?, dari=?, status_anak=?, nama_ayah=?,"
                    + " nama_ibu=?, alamat=?, penghasilan_ortu=?, pendidikan_ayah=?, pendidikan_ibu=?,"
                    + " no_hp=? ,administrasi=?, foto=?, ijazah=? where no_pendaftar=?";
            Class.forName("com.mysql.jdbc.Driver");
            Connection connect = DriverManager.getConnection("jdbc:mysql:///skripsi", "root", "");
            PreparedStatement tulis = connect.prepareStatement(sql);
            tulis.setString(1, p_nama.getText());
            tulis.setString(2, JenKel);
            tulis.setString(3, p_tempat.getText());
            tulis.setString(4, Tanggal);
            tulis.setString(5, p_cbpendidikan.getSelectedItem().toString());
            tulis.setString(6, p_cbmasukL.getSelectedItem().toString());
            tulis.setString(7, p_cbanakke.getSelectedItem().toString());
            tulis.setString(8, p_cbdarike.getSelectedItem().toString());
            tulis.setString(9, p_cbstatus.getSelectedItem().toString());
            tulis.setString(10, p_nayah.getText());
            tulis.setString(11, p_nibu.getText());
            tulis.setString(12, p_alamat.getText());
            tulis.setString(13, p_cbpenghasilan.getSelectedItem().toString());
            tulis.setString(14, p_penayah.getSelectedItem().toString());
            tulis.setString(15, p_pendibu.getSelectedItem().toString());
            tulis.setString(16, p_nope.getText());
            tulis.setString(17, adminis);
            tulis.setString(18, ft);
            tulis.setString(19, ij);
            tulis.setString(20, p_pendaftaran.getText());
            tulis.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Berhasil Di Edit");
            jRadioButton1.setSelected(false);
            jRadioButton2.setSelected(false);
            bersih();
            autokode();
            //refresh();
            //Tampil_Tabel();
        } catch (ClassNotFoundException | SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(this, e);
        }

    }//GEN-LAST:event_p_editActionPerformed

    private void p_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_hapusActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "Delete from pdb where no_pendaftar=?";
            Class.forName("com.mysql.jdbc.Driver");
            Connection koneksi = DriverManager.getConnection("jdbc:mysql:///skripsi", "root", "");
            PreparedStatement tulis = koneksi.prepareStatement(sql);
            tulis.setString(1, p_pendaftaran.getText());
            tulis.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Berhasil Di Hapus ");
            bersih();
            //refresh();
            //Tampil_Tabel();
            //input();
        } catch (ClassNotFoundException | SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(this, e);
        }
        autokode();

    }//GEN-LAST:event_p_hapusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        p_pendaftaran.setEnabled(true);
        p_edit.setEnabled(true);
        p_hapus.setEnabled(true);
        p_simpan.setEnabled(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void p_bersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_bersihActionPerformed
        // TODO add your handling code here:
        bersih();
        autokode();

    }//GEN-LAST:event_p_bersihActionPerformed

    private void p_pendaftaranKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_p_pendaftaranKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                // String no_pendaftar = p_pendaftaran.getText();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                //String Tanggal = String.valueOf(sdf.format(J_date.getDate()));
                Date dateValue = null;
                try {
                    //String query = "SELECT * FROM tb_penilaian WHERE (no_penilaian='" + idpenilaian + "') AND (id_siswi= '"+idsiswi+"')";
                    String query = "SELECT * FROM pdb WHERE no_pendaftar = '" + p_pendaftaran.getText() + "'";
                    Statement st = con.createStatement();
                    ResultSet rs = st.executeQuery(query);

                    while (rs.next()) {

                        String np = rs.getString("no_pendaftar");
                        String nama = rs.getString("nama");
                        String jengkeldb = rs.getString("jenkel");
                        String tempat_lahirdb = rs.getString("tempat_lahir");
                        String tanggal_lahirdb = rs.getString("tanggal_lahir");
                        String pendidikandb = rs.getString("pendidikan");
                        String masuk_lembagadb = rs.getString("masuk_lembaga");
                        String anak_kedb = rs.getString("anak_ke");
                        String daridb = rs.getString("dari");
                        String status_anakdb = rs.getString("status_anak");
                        String nama_ayahdb = rs.getString("nama_ayah");
                        String nama_ibudb = rs.getString("nama_ibu");
                        String alamatdb = rs.getString("alamat");
                        String penghasilan_ortudb = rs.getString("penghasilan_ortu");
                        String pendidikan_ayahdb = rs.getString("pendidikan_ayah");
                        String pendidikan_ibudb = rs.getString("pendidikan_ibu");
                        String no_hpdb = rs.getString("no_hp");
                        String administrasidb = rs.getString("administrasi");
                        String fotodb = rs.getString("foto");
                        String ijazahdb = rs.getString("ijazah");

                        p_pendaftaran.setText(np);
                        p_nama.setText(nama);
                        p_tempat.setText(tempat_lahirdb);
                        dateValue = sdf.parse(tanggal_lahirdb);
                        p_date.setDate(dateValue);
                        p_cbpendidikan.setSelectedItem(pendidikandb);
                        p_cbmasukL.setSelectedItem(masuk_lembagadb);
                        p_cbanakke.setSelectedItem(anak_kedb);
                        p_cbdarike.setSelectedItem(daridb);
                        p_cbstatus.setSelectedItem(status_anakdb);
                        p_nayah.setText(nama_ayahdb);
                        p_nibu.setText(nama_ibudb);
                        p_cbpenghasilan.setSelectedItem(penghasilan_ortudb);
                        p_penayah.setSelectedItem(pendidikan_ayahdb);
                        p_pendibu.setSelectedItem(pendidikan_ibudb);
                        p_alamat.setText(alamatdb);
                        p_nope.setText(no_hpdb);

                        if (jengkeldb.equals("Laki-Laki")) {
                            jRadioButton1.setSelected(true);
                            jRadioButton2.setSelected(false);
                        } else {
                            jRadioButton2.setSelected(true);
                            jRadioButton1.setSelected(false);
                        }

                        if (administrasidb.equals("Ada")) {
                            p_cbadmin.setSelected(true);

                        } else {

                            p_cbadmin.setSelected(false);
                        }
                        if (fotodb.equals("Ada")) {
                            p_cbfoto.setSelected(true);

                        } else {

                            p_cbfoto.setSelected(false);
                        }
                        if (ijazahdb.equals("Ada")) {
                            p_cbijazah.setSelected(true);

                        } else {

                            p_cbijazah.setSelected(false);
                        }

                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Tidak Ditekan Enter");
        }
    }//GEN-LAST:event_p_pendaftaranKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_data_pdb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_data_pdb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_data_pdb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_data_pdb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                form_data_pdb dialog = new form_data_pdb(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void autokode() {
        try {

            String query = "SELECT MAX(right(no_pendaftar,5))AS no FROM pdb";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                if (rs.first() == false) {
                    p_pendaftaran.setText("000001");
                } else {
                    rs.last();
                    int auto_id = rs.getInt(1) + 1;
                    String no = String.valueOf(auto_id);
                    int nolong = no.length();
                    for (int a = 0; a < 6 - nolong; a++) {
                        no = "0" + no;
                    }

                    p_pendaftaran.setText(no);
                }
            }
            rs.close();
            st.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR:\n" + e.toString(), "kesalahan", JOptionPane.WARNING_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField p_alamat;
    private javax.swing.JButton p_bersih;
    private javax.swing.JCheckBox p_cbadmin;
    private javax.swing.JComboBox p_cbanakke;
    private javax.swing.JComboBox p_cbdarike;
    private javax.swing.JCheckBox p_cbfoto;
    private javax.swing.JCheckBox p_cbijazah;
    private javax.swing.JComboBox p_cbmasukL;
    private javax.swing.JComboBox p_cbpendidikan;
    private javax.swing.JComboBox p_cbpenghasilan;
    private javax.swing.JComboBox p_cbstatus;
    private com.toedter.calendar.JDateChooser p_date;
    private javax.swing.JButton p_edit;
    private javax.swing.JButton p_hapus;
    private javax.swing.JTextField p_nama;
    private javax.swing.JTextField p_nayah;
    private javax.swing.JTextField p_nibu;
    private javax.swing.JTextField p_nope;
    private javax.swing.JComboBox p_penayah;
    private javax.swing.JTextField p_pendaftaran;
    private javax.swing.JComboBox p_pendibu;
    private javax.swing.JButton p_simpan;
    private javax.swing.JTextField p_tempat;
    // End of variables declaration//GEN-END:variables
}
