/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skripsi;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Ulil_Mz
 */
public class form_datatahfidz extends javax.swing.JDialog {

    private static Connection con;

    /**
     * Creates new form form_datatahfidz
     */
    public form_datatahfidz(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            con = koneksidb.getConnection();
            System.out.println("Koneksi Sukses");
        } catch (Exception e) {
        }
        autokode3();
        t_nama.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        t_noinduk = new javax.swing.JTextField();
        t_nama = new javax.swing.JTextField();
        t_alamat = new javax.swing.JTextField();
        t_cblaki = new javax.swing.JRadioButton();
        t_cbpr = new javax.swing.JRadioButton();
        t_tempat = new javax.swing.JTextField();
        t_tanggal = new com.toedter.calendar.JDateChooser();
        t_cbtarget = new javax.swing.JComboBox();
        t_wali = new javax.swing.JTextField();
        t_nope = new javax.swing.JTextField();
        t_tambah = new javax.swing.JButton();
        t_edit = new javax.swing.JButton();
        t_hapus = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel1.setText("No.Induk");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(31, 77, 50, 16);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(31, 119, 30, 16);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel3.setText("Alamat");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(383, 188, 38, 16);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel4.setText("Jenis Kelamin");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(31, 195, 73, 16);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel5.setText("Tempat dan Tanggal Lahir");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(31, 159, 140, 16);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel6.setText("Target Hafalan");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(383, 81, 79, 16);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel7.setText(" Wali / Orang Tua");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(383, 121, 95, 16);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel8.setText("No. HP");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(383, 159, 38, 16);
        getContentPane().add(t_noinduk);
        t_noinduk.setBounds(193, 75, 93, 20);
        getContentPane().add(t_nama);
        t_nama.setBounds(193, 119, 128, 20);
        getContentPane().add(t_alamat);
        t_alamat.setBounds(546, 188, 120, 51);

        buttonGroup1.add(t_cblaki);
        t_cblaki.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        t_cblaki.setText("Laki-Laki");
        getContentPane().add(t_cblaki);
        t_cblaki.setBounds(193, 195, 71, 23);

        buttonGroup1.add(t_cbpr);
        t_cbpr.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        t_cbpr.setText("Perempuan");
        getContentPane().add(t_cbpr);
        t_cbpr.setBounds(282, 195, 79, 23);
        getContentPane().add(t_tempat);
        t_tempat.setBounds(193, 157, 61, 20);
        getContentPane().add(t_tanggal);
        t_tanggal.setBounds(264, 157, 91, 20);

        t_cbtarget.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        t_cbtarget.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5 Juz", "10 Juz", "15 Juz", "30 Juz", " " }));
        getContentPane().add(t_cbtarget);
        t_cbtarget.setBounds(546, 81, 57, 20);
        getContentPane().add(t_wali);
        t_wali.setBounds(546, 119, 102, 20);
        getContentPane().add(t_nope);
        t_nope.setBounds(546, 157, 102, 20);

        t_tambah.setText("TAMBAH");
        t_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_tambahActionPerformed(evt);
            }
        });
        getContentPane().add(t_tambah);
        t_tambah.setBounds(193, 314, 73, 23);

        t_edit.setText("EDIT");
        getContentPane().add(t_edit);
        t_edit.setBounds(293, 314, 68, 23);

        t_hapus.setText("HAPUS");
        getContentPane().add(t_hapus);
        t_hapus.setBounds(395, 314, 65, 23);

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(292, 69, 51, 32);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/latar1.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 690, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        //String Tanggal = String.valueOf(sdf.format(J_date.getDate()));
        Date dateValue = null;
        try {
            String query = "SELECT * FROM peserta_tahfidz WHERE no_induk = '" + t_noinduk.getText() + "'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {

                String np = rs.getString("no_induk");
                String nama = rs.getString("nama");
                String jengkeldb = rs.getString("jenkel");
                String tempat_lahirdb = rs.getString("tempat_lahir");
                String tanggal_lahirdb = rs.getString("tanggal_lahir");
                String pendidikandb = rs.getString("pendidikan");
                String masuk_lembagadb = rs.getString("masuk_lembaga");
                String anak_kedb = rs.getString("anak_ke");
                String daridb = rs.getString("dari");
                String status_anakdb = rs.getString("status_anak");
                String nama_ayahdb = rs.getString("nama_ayah");
                String nama_ibudb = rs.getString("nama_ibu");
                String alamatdb = rs.getString("alamat");
                String penghasilan_ortudb = rs.getString("penghasilan_ortu");
                String pendidikan_ayahdb = rs.getString("pendidikan_ayah");
                String pendidikan_ibudb = rs.getString("pendidikan_ibu");
                String no_hpdb = rs.getString("no_hp");
                String administrasidb = rs.getString("administrasi");
                String fotodb = rs.getString("foto");
                String ijazahdb = rs.getString("ijazah");
                String targetdb = rs.getString("target_hafalan");

                t_noinduk.setText(np);
                t_nama.setText(nama);
                t_tempat.setText(tempat_lahirdb);
                dateValue = sdf.parse(tanggal_lahirdb);
                t_tanggal.setDate(dateValue);
                t_cbtarget.setSelectedItem(targetdb);
                t_wali.setText(nama_ayahdb);
                t_nope.setText(no_hpdb);
                t_alamat.setText(alamatdb);

                if (jengkeldb.equals("Laki-Laki")) {
                    t_cblaki.setSelected(true);
                    t_cbpr.setSelected(false);
                } else {
                    t_cbpr.setSelected(true);
                    t_cblaki.setSelected(false);
                }

            }
        } catch (SQLException | ParseException e) {
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void t_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_tambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_tambahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_datatahfidz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_datatahfidz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_datatahfidz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_datatahfidz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                form_datatahfidz dialog = new form_datatahfidz(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void autokode3() {
        try {

            String query = "SELECT MAX(right(no_induk,5))AS no FROM peserta_tahfidz";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                if (rs.first() == false) {
                    t_noinduk.setText("1711001");
                } else {
                    rs.last();
                    int auto_id = rs.getInt(1) + 1;
                    String no = String.valueOf(auto_id);
                    int nolong = no.length();
                    for (int a = 0; a < 1 - nolong; a++) {
                        no = "171100" + no;
                    }

                    t_noinduk.setText("171100" + no);

                }
            }
            rs.close();
            st.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR:\n" + e.toString(), "kesalahan", JOptionPane.WARNING_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField t_alamat;
    private javax.swing.JRadioButton t_cblaki;
    private javax.swing.JRadioButton t_cbpr;
    private javax.swing.JComboBox t_cbtarget;
    private javax.swing.JButton t_edit;
    private javax.swing.JButton t_hapus;
    private javax.swing.JTextField t_nama;
    private javax.swing.JTextField t_noinduk;
    private javax.swing.JTextField t_nope;
    private javax.swing.JButton t_tambah;
    private com.toedter.calendar.JDateChooser t_tanggal;
    private javax.swing.JTextField t_tempat;
    private javax.swing.JTextField t_wali;
    // End of variables declaration//GEN-END:variables
}
