/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skripsi;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ulil_Mz
 */
public class form_tesseleksi extends javax.swing.JDialog {

    private static Connection con;
    private Object tabel;
    private DefaultTableModel tabel2;
    Float n1, n2, n3, tn1, tn2, tn3, jmltotal, p;

    public void bersih() {
        t_noseleksi.setText(null);
        t_nopen.setText(null);
        t_nama.setText("..........");
        t_kefasihan.setText("0");
        t_kelancaran.setText("0");
        t_kebenaran.setText("0");
        t_tokefasihan.setText(".....");
        t_tokelancaran.setText(".....");
        t_tokebenaran.setText(".....");
        t_jumtotal.setText(null);
        t_keterangan.setText(".....");
        t_noinduk.setText(null);
        t_target.setText(null);
    }

    /**
     * Creates new form form_tesseleksi
     */
    public form_tesseleksi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        String[] data = {"No Seleksi", "No Pendaftar", "Nama", "Kefasihan", "Kelancaran", "Kebenaran", "Jumlah Total",
            "Keterangan", "No Induk", "Target Hafalan"};
        tabel2 = new DefaultTableModel(data, 0);
        try {
            con = koneksidb.getConnection();
            System.out.println("Koneksi Sukses");
        } catch (Exception e) {
        }

        setLocationRelativeTo(null);
        autokode();
        autokode2();
        //autokode3();
        Tampil_Tabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t_nopen = new javax.swing.JTextField();
        t_btcari = new javax.swing.JButton();
        t_nama = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        t_kefasihan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        t_kelancaran = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        t_kebenaran = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        t_jumtotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_tabel = new javax.swing.JTable();
        t_btsimpan = new javax.swing.JButton();
        t_btedit = new javax.swing.JButton();
        t_bthapus = new javax.swing.JButton();
        t_btproses = new javax.swing.JButton();
        t_keterangan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t_target = new javax.swing.JTextField();
        t_noinduk = new javax.swing.JTextField();
        t_tokefasihan = new javax.swing.JLabel();
        t_tokelancaran = new javax.swing.JLabel();
        t_tokebenaran = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        t_noseleksi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel3.setText("No. Penndaftara");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel4.setText("Nama");

        t_btcari.setText("Cari");
        t_btcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_btcariActionPerformed(evt);
            }
        });

        t_nama.setText("...............");

        jLabel7.setText("Kefashihan");

        jLabel8.setText("Kelancaran");

        jLabel9.setText("Kebenaran");

        t_kefasihan.setText("0");
        t_kefasihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_kefasihanActionPerformed(evt);
            }
        });
        t_kefasihan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_kefasihanFocusLost(evt);
            }
        });
        t_kefasihan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_kefasihanKeyReleased(evt);
            }
        });

        jLabel10.setText("X");

        jLabel11.setText("40 %");

        jLabel12.setText("=");

        t_kelancaran.setText("0");
        t_kelancaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_kelancaranKeyReleased(evt);
            }
        });

        jLabel13.setText("X");

        jLabel14.setText("30 %");

        jLabel15.setText("=");

        t_kebenaran.setText("0");
        t_kebenaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_kebenaranKeyReleased(evt);
            }
        });

        jLabel16.setText("X");

        jLabel17.setText("30 %");

        jLabel18.setText("=");

        jLabel19.setText("Jumlah Total");

        jLabel20.setText("Keterangan");

        t_tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        t_tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(t_tabel);

        t_btsimpan.setText("SIMPAN");
        t_btsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_btsimpanActionPerformed(evt);
            }
        });

        t_btedit.setText("EDIT");
        t_btedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_bteditActionPerformed(evt);
            }
        });

        t_bthapus.setText("HAPUS");
        t_bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_bthapusActionPerformed(evt);
            }
        });

        t_btproses.setText("Proses");
        t_btproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_btprosesActionPerformed(evt);
            }
        });

        t_keterangan.setText("...................");

        jLabel2.setText("No Induk");

        jLabel5.setText("Target Hafalan");

        t_target.setEnabled(false);

        t_noinduk.setEnabled(false);
        t_noinduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_noindukActionPerformed(evt);
            }
        });

        t_tokefasihan.setText("........");

        t_tokelancaran.setText("........");

        t_tokebenaran.setText(".......");

        jLabel1.setText("No Seleksi");

        jButton1.setText("REFRESH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(t_nopen)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t_btcari))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(56, 56, 56)
                                                .addComponent(t_noseleksi)
                                                .addGap(32, 32, 32))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel9))
                                                .addGap(51, 51, 51)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(t_nama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(t_kebenaran, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                            .addComponent(t_kefasihan)
                                                            .addComponent(t_kelancaran, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel11)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel12)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(t_tokefasihan))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel14)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel15)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(t_tokelancaran))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel17)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel18)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(t_tokebenaran)))))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t_jumtotal)
                            .addComponent(t_keterangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t_target)
                            .addComponent(t_noinduk, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_btproses, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t_btsimpan)
                .addGap(18, 18, 18)
                .addComponent(t_btedit, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(t_bthapus)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(t_noseleksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(t_nopen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_btcari))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(t_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(t_kefasihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(t_tokefasihan))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t_kelancaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel8)
                            .addComponent(t_tokelancaran))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t_kebenaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel9)
                            .addComponent(t_tokebenaran))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(54, 54, 54))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(t_jumtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t_btproses))
                                .addGap(18, 18, 18)
                                .addComponent(t_keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(t_noinduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(t_target, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(11, 11, 11))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(t_btsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_btedit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_bthapus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_noindukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_noindukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_noindukActionPerformed

    private void t_btprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_btprosesActionPerformed
        // TODO add your handling code here:

        Float n1, n2, n3, tn1, tn2, tn3, jmltotal;
        n1 = Float.parseFloat(t_tokefasihan.getText());
        n2 = Float.parseFloat(t_tokelancaran.getText());
        n3 = Float.parseFloat(t_tokebenaran.getText());
        jmltotal = n1 + n2 + n3;
        t_jumtotal.setText(String.valueOf(jmltotal));

        if (jmltotal > 79) {
            t_keterangan.setText("LULUS");
            t_noinduk.enable(true);

            t_target.enable(true);
            t_target.requestFocus();
            autokode3();

        } else {
            t_keterangan.setText("TIDAK LULUS");
        }


    }//GEN-LAST:event_t_btprosesActionPerformed

    private void t_kefasihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_kefasihanActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_t_kefasihanActionPerformed

    private void t_kefasihanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_kefasihanKeyReleased
        // TODO add your handling code here:
        try {
            n1 = Float.parseFloat(t_kefasihan.getText());
            tn1 = n1 * 40 / 100;
            t_tokefasihan.setText(String.valueOf(tn1));
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(this, "Masih kosong");
        }


    }//GEN-LAST:event_t_kefasihanKeyReleased

    private void t_kefasihanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_kefasihanFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_t_kefasihanFocusLost

    private void t_kelancaranKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_kelancaranKeyReleased
        // TODO add your handling code here:
        try {
            n2 = Float.parseFloat(t_kelancaran.getText());

            tn2 = n2 * 30 / 100;
            t_tokelancaran.setText(String.valueOf(tn2));
        } catch (Exception e) {
        }

    }//GEN-LAST:event_t_kelancaranKeyReleased

    private void t_kebenaranKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_kebenaranKeyReleased
        // TODO add your handling code here:
        try {
            n1 = Float.parseFloat(t_kebenaran.getText());

            tn1 = n1 * 30 / 100;
            t_tokebenaran.setText(String.valueOf(tn1));
        } catch (Exception e) {
        }


    }//GEN-LAST:event_t_kebenaranKeyReleased

    private void t_btsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_btsimpanActionPerformed
        // TODO add your handling code here:
        String ket = t_keterangan.getText().toString();
        if (ket.equals("LULUS")) {
            try {
                String query = "SELECT * FROM pdb WHERE no_pendaftar = '" + t_nopen.getText() + "'";
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(query);
                while (rs.next()) {
                    String np = rs.getString("no_pendaftar");
                    String nama = rs.getString("nama");
                    String jengkeldb = rs.getString("jenkel");
                    String tempat_lahirdb = rs.getString("tempat_lahir");
                    String tanggal_lahirdb = rs.getString("tanggal_lahir");
                    String pendidikandb = rs.getString("pendidikan");
                    String masuk_lembagadb = rs.getString("masuk_lembaga");
                    String anak_kedb = rs.getString("anak_ke");
                    String daridb = rs.getString("dari");
                    String status_anakdb = rs.getString("status_anak");
                    String nama_ayahdb = rs.getString("nama_ayah");
                    String nama_ibudb = rs.getString("nama_ibu");
                    String alamatdb = rs.getString("alamat");
                    String penghasilan_ortudb = rs.getString("penghasilan_ortu");
                    String pendidikan_ayahdb = rs.getString("pendidikan_ayah");
                    String pendidikan_ibudb = rs.getString("pendidikan_ibu");
                    String no_hpdb = rs.getString("no_hp");
                    String administrasidb = rs.getString("administrasi");
                    String fotodb = rs.getString("foto");
                    String ijazahdb = rs.getString("ijazah");

                    //simpan k tahfidz
                    try {
                        String sql = "insert into peserta_tahfidz values (?,?,?,?,?,?,?,?,?)";
                        Class.forName("com.mysql.jdbc.Driver");
                        Connection koneksi = DriverManager.getConnection("jdbc:mysql:///skripsi", "root", "");
                        PreparedStatement tulis = koneksi.prepareStatement(sql);
                        tulis.setString(1, t_noinduk.getText());
                        tulis.setString(2, nama);
                        tulis.setString(3, tempat_lahirdb);
                        tulis.setString(4, tanggal_lahirdb);
                        tulis.setString(5, jengkeldb);
                        tulis.setString(6, t_target.getText());
                        tulis.setString(7, nama_ayahdb);
                        tulis.setString(8, no_hpdb);
                        tulis.setString(9, alamatdb);
                        tulis.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Data Santri Lulus Berhasil Di Simpan Di Tabel Santri Tahfidz Baru");
                        bersih();

                    } catch (Exception e) {
                    }

                }

            } catch (Exception e) {
            }

        } else {
            JOptionPane.showMessageDialog(this, "data santri tidak lulus berhasil disimpan pada tabel tes seleksi");

        }

        try {
            String sql = "insert into tes_seleksi values (?,?,?,?,?,?,?,?,?,?)";
            Class.forName("com.mysql.jdbc.Driver");
            Connection koneksi = DriverManager.getConnection("jdbc:mysql:///skripsi", "root", "");
            PreparedStatement tl = koneksi.prepareStatement(sql);
            tl.setString(1, t_noseleksi.getText());
            tl.setString(2, t_nopen.getText());
            tl.setString(3, t_nama.getText());
            tl.setString(4, t_tokefasihan.getText());
            tl.setString(5, t_tokelancaran.getText());
            tl.setString(6, t_tokebenaran.getText());
            tl.setString(7, t_jumtotal.getText());
            tl.setString(8, t_keterangan.getText());
            tl.setString(9, t_noinduk.getText());
            tl.setString(10, t_target.getText());
            tl.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Berhasil Di Simpan");
            bersih();
            Tampil_Tabel();
            //dispose();
        } catch (ClassNotFoundException | SQLException | HeadlessException e) {
        }

        autokode();
        autokode2();

    }//GEN-LAST:event_t_btsimpanActionPerformed
    public void Tampil_Tabel() {
        tabel2.setNumRows(0);
        try {
            String sql = "Select * from tes_seleksi";
            Class.forName("com.mysql.jdbc.Driver");
            Connection P21Q = DriverManager.getConnection("jdbc:mysql:///skripsi", "root", "");
            PreparedStatement UR = P21Q.prepareStatement(sql);
            ResultSet Tampil = UR.executeQuery();
            while (Tampil.next()) {
                tabel2.addRow(new Object[]{Tampil.getString(1), Tampil.getString(2), Tampil.getString(3), Tampil.getString(4),
                    Tampil.getString(5), Tampil.getString(6), Tampil.getString(7), Tampil.getString(8), Tampil.getString(9),
                    Tampil.getString(10)});
                t_tabel.setModel(tabel2);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    private void t_btcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_btcariActionPerformed
        // TODO add your handling code here:

        try {
            //String query = "SELECT * FROM tb_penilaian WHERE (no_penilaian='" + idpenilaian + "') AND (id_siswi= '"+idsiswi+"')";
            String query = "SELECT * FROM pdb WHERE no_pendaftar = '" + t_nopen.getText() + "'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);

            if (rs.next()) {
                String nama = rs.getString("nama");

                t_nama.setText(nama);

            } else {
                JOptionPane.showMessageDialog(this, "Belum Terdaftar");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_t_btcariActionPerformed

    private void t_bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_bteditActionPerformed
        // TODO add your handling code here:
        try {

            String sql = "Update tes_seleksi Set no_pendaftar=?, nama=?,kefashihan=?, kelancaran=?, "
                    + "kebenaran=?, total_nilai=?, keterangan=?, no_induk=?, target_hafalan=? where no_seleksi=?";
            Class.forName("com.mysql.jdbc.Driver");
            Connection connect = DriverManager.getConnection("jdbc:mysql:///skripsi", "root", "");
            PreparedStatement tulis = connect.prepareStatement(sql);
            tulis.setString(1, t_nopen.getText());
            tulis.setString(2, t_nama.getText());
            tulis.setString(3, t_tokefasihan.getText());
            tulis.setString(4, t_tokelancaran.getText());
            tulis.setString(5, t_tokebenaran.getText());
            tulis.setString(6, t_jumtotal.getText());
            tulis.setString(7, t_keterangan.getText());
            tulis.setString(8, t_noinduk.getText());
            tulis.setString(9, t_target.getText());
            tulis.setString(10, t_noseleksi.getText());
            tulis.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Berhasil Di Edit");
            bersih();
            Tampil_Tabel();
            autokode();
            autokode2();
        } catch (ClassNotFoundException | SQLException e) {
        }
    }//GEN-LAST:event_t_bteditActionPerformed

    private void t_bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_bthapusActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "Delete from tes_seleksi where no_seleksi=?";
            Class.forName("com.mysql.jdbc.Driver");
            Connection koneksi = DriverManager.getConnection("jdbc:mysql:///skripsi", "root", "");
            PreparedStatement tulis = koneksi.prepareStatement(sql);
            tulis.setString(1, t_noseleksi.getText());
            tulis.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Berhasil Di Hapus ");
            bersih();
            //refresh();
            Tampil_Tabel();
            autokode();
            autokode2();
            //input();
        } catch (ClassNotFoundException | SQLException | HeadlessException e) {
        }
    }//GEN-LAST:event_t_bthapusActionPerformed

    private void t_tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_tabelMouseClicked
        // TODO add your handling code here
        int i = t_tabel.getSelectedRow();
        if (i == -1) {
        } else {
            String Klik0 = (String) t_tabel.getValueAt(i, 0);
            String Klik1 = (String) t_tabel.getValueAt(i, 1);
            String Klik2 = (String) t_tabel.getValueAt(i, 2);
            String Klik3 = (String) t_tabel.getValueAt(i, 3);
            String Klik4 = (String) t_tabel.getValueAt(i, 4);
            String Klik5 = (String) t_tabel.getValueAt(i, 5);
            String Klik6 = (String) t_tabel.getValueAt(i, 6);
            String Klik7 = (String) t_tabel.getValueAt(i, 7);
            String Klik8 = (String) t_tabel.getValueAt(i, 8);
            String Klik9 = (String) t_tabel.getValueAt(i, 9);

            try {
                String sql = "Select * from tes_seleksi WHERE no_seleksi=?";
                Class.forName("com.mysql.jdbc.Driver");
                Connection P21Q = DriverManager.getConnection("jdbc:mysql:///Skripsi", "root", "");
                PreparedStatement UR = P21Q.prepareStatement(sql);
                t_noseleksi.setText(Klik0);
                t_nopen.setText(Klik1);
                t_nama.setText(Klik2);
                t_tokefasihan.setText(Klik3);
                t_tokelancaran.setText(Klik4);
                t_tokebenaran.setText(Klik5);
                t_jumtotal.setText(Klik6);
                t_keterangan.setText(Klik7);
                t_noinduk.setText(Klik8);
                t_target.setText(Klik9);

            } catch (ClassNotFoundException | SQLException e) {
            }
        }
    }//GEN-LAST:event_t_tabelMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        bersih();
        autokode();
        autokode2();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_tesseleksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_tesseleksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_tesseleksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_tesseleksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                form_tesseleksi dialog = new form_tesseleksi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void autokode() {
        try {

            String query = "SELECT MAX(right(no_seleksi,5))AS no FROM tes_seleksi";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                if (rs.first() == false) {
                    t_noseleksi.setText("000001");
                } else {
                    rs.last();
                    int auto_id = rs.getInt(1) + 1;
                    String no = String.valueOf(auto_id);
                    int nolong = no.length();
                    for (int a = 0; a < 6 - nolong; a++) {
                        no = no;
                    }

                    t_noseleksi.setText(no);
                }
            }
            rs.close();
            st.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR:\n" + e.toString(), "kesalahan", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void autokode2() {
        try {

            String query = "SELECT MAX(right(no_seleksi,5))AS no FROM tes_seleksi";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                if (rs.first() == false) {
                    t_nopen.setText("000001");
                } else {
                    rs.last();
                    int auto_id = rs.getInt(1) + 1;
                    String no = String.valueOf(auto_id);
                    int nolong = no.length();
                    for (int a = 0; a < 6 - nolong; a++) {
                        no = "0" + no;
                    }

                    t_nopen.setText(no);
                }
            }
            rs.close();
            st.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR:\n" + e.toString(), "kesalahan", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void autokode3() {
        try {

            String query = "SELECT MAX(right(no_induk,5))AS no FROM peserta_tahfidz";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                if (rs.first() == false) {
                    t_noinduk.setText("1711001");
                } else {
                    rs.last();
                    int auto_id = rs.getInt(1) + 1;
                    String no = String.valueOf(auto_id);
                    int nolong = no.length();
                    for (int a = 0; a < 1 - nolong; a++) {
                        no = no;
                    }

                    t_noinduk.setText("171100" + no);
                }
            }
            rs.close();
            st.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR:\n" + e.toString(), "kesalahan", JOptionPane.WARNING_MESSAGE);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton t_btcari;
    private javax.swing.JButton t_btedit;
    private javax.swing.JButton t_bthapus;
    private javax.swing.JButton t_btproses;
    private javax.swing.JButton t_btsimpan;
    private javax.swing.JTextField t_jumtotal;
    private javax.swing.JTextField t_kebenaran;
    private javax.swing.JTextField t_kefasihan;
    private javax.swing.JTextField t_kelancaran;
    private javax.swing.JLabel t_keterangan;
    private javax.swing.JLabel t_nama;
    private javax.swing.JTextField t_noinduk;
    private javax.swing.JTextField t_nopen;
    private javax.swing.JTextField t_noseleksi;
    private javax.swing.JTable t_tabel;
    private javax.swing.JTextField t_target;
    private javax.swing.JLabel t_tokebenaran;
    private javax.swing.JLabel t_tokefasihan;
    private javax.swing.JLabel t_tokelancaran;
    // End of variables declaration//GEN-END:variables
}
