/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skripsi;

import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author madchen
 */
public class Frame_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Menu
     */
    public Frame_Menu() {
        //this.setUndecorated(true);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
         int xsize = (int) tk.getScreenSize().getWidth();
         int ysize = (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_data_pdb = new javax.swing.JButton();
        bt_data_tahfidz = new javax.swing.JButton();
        bt_nilai_harian = new javax.swing.JButton();
        bt_pentashih = new javax.swing.JButton();
        bt_petugas = new javax.swing.JButton();
        bt_tes_seleksi = new javax.swing.JButton();
        bt_ujian = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_data_pdb.setText("Data PDB");
        bt_data_pdb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_data_pdbActionPerformed(evt);
            }
        });

        bt_data_tahfidz.setText("Data Tahfidz");
        bt_data_tahfidz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_data_tahfidzActionPerformed(evt);
            }
        });

        bt_nilai_harian.setText("Penilaian Harian");
        bt_nilai_harian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_nilai_harianActionPerformed(evt);
            }
        });

        bt_pentashih.setText("Pentashih");
        bt_pentashih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pentashihActionPerformed(evt);
            }
        });

        bt_petugas.setText("Petugas");
        bt_petugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_petugasActionPerformed(evt);
            }
        });

        bt_tes_seleksi.setText("Tes Seleksi");
        bt_tes_seleksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tes_seleksiActionPerformed(evt);
            }
        });

        bt_ujian.setText("Ujian");
        bt_ujian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ujianActionPerformed(evt);
            }
        });

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_data_pdb)
                            .addComponent(bt_nilai_harian)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(bt_petugas)))
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_tes_seleksi)
                    .addComponent(bt_pentashih)
                    .addComponent(bt_data_tahfidz))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(bt_ujian))
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_data_pdb)
                    .addComponent(bt_data_tahfidz))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_nilai_harian)
                    .addComponent(bt_pentashih))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_petugas)
                    .addComponent(bt_tes_seleksi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_ujian)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_data_pdbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_data_pdbActionPerformed
        // TODO add your handling code here:
       new form_data_pdb(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_bt_data_pdbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt_data_tahfidzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_data_tahfidzActionPerformed
        // TODO add your handling code here:
          new form_datatahfidz(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_bt_data_tahfidzActionPerformed

    private void bt_nilai_harianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_nilai_harianActionPerformed
        // TODO add your handling code here:
          new form_penilaianharian(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_bt_nilai_harianActionPerformed

    private void bt_pentashihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pentashihActionPerformed
        // TODO add your handling code here:
          new form_pentashih(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_bt_pentashihActionPerformed

    private void bt_petugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_petugasActionPerformed
        // TODO add your handling code here:
          new form_petugas(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_bt_petugasActionPerformed

    private void bt_tes_seleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tes_seleksiActionPerformed
        // TODO add your handling code here:
          new form_tesseleksi(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_bt_tes_seleksiActionPerformed

    private void bt_ujianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ujianActionPerformed
        // TODO add your handling code here:
          new form_ujiantriwulan(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_bt_ujianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new Frame_Menu().setVisible(true);
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_data_pdb;
    private javax.swing.JButton bt_data_tahfidz;
    private javax.swing.JButton bt_nilai_harian;
    private javax.swing.JButton bt_pentashih;
    private javax.swing.JButton bt_petugas;
    private javax.swing.JButton bt_tes_seleksi;
    private javax.swing.JButton bt_ujian;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
