/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skripsi;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author madchen
 */
public class Jdialog_datatahfidz extends javax.swing.JDialog {

    private static Connection con;

    /**
     * Creates new form Jdialog_datatahfidz
     */
    public Jdialog_datatahfidz(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            con = koneksidb.getConnection();
            System.out.println("Koneksi Sukses");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Koneksi");
        }
        bersih();
        autokode3();
        t_nama.requestFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        t_noinduk = new javax.swing.JTextField();
        t_nama = new javax.swing.JTextField();
        t_alamat = new javax.swing.JTextField();
        t_cblaki = new javax.swing.JRadioButton();
        t_cbpr = new javax.swing.JRadioButton();
        t_tempat = new javax.swing.JTextField();
        t_tanggal = new com.toedter.calendar.JDateChooser();
        t_cbtarget = new javax.swing.JComboBox();
        t_wali = new javax.swing.JTextField();
        t_nope = new javax.swing.JTextField();
        t_tambah = new javax.swing.JButton();
        t_edit = new javax.swing.JButton();
        t_hapus = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel1.setText("No.Induk");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel3.setText("Alamat");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel4.setText("Jenis Kelamin");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel5.setText("Tempat dan Tanggal Lahir");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel6.setText("Target Hafalan");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel7.setText(" Wali / Orang Tua");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel8.setText("No. HP");

        t_noinduk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_noindukKeyPressed(evt);
            }
        });

        buttonGroup1.add(t_cblaki);
        t_cblaki.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        t_cblaki.setText("Laki-Laki");

        buttonGroup1.add(t_cbpr);
        t_cbpr.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        t_cbpr.setText("Perempuan");

        t_cbtarget.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        t_cbtarget.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5 Juz", "10 Juz", "15 Juz", "30 Juz", " " }));

        t_tambah.setText("TAMBAH");
        t_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_tambahActionPerformed(evt);
            }
        });

        t_edit.setText("EDIT");
        t_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_editActionPerformed(evt);
            }
        });

        t_hapus.setText("HAPUS");
        t_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_hapusActionPerformed(evt);
            }
        });

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("BERSIH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/latar1.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(383, 383, 383)
                            .addComponent(jLabel6))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(193, 193, 193)
                            .addComponent(t_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(jLabel5)
                            .addGap(93, 93, 93)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(119, 119, 119)
                                    .addComponent(jLabel8))
                                .addComponent(t_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(125, 125, 125)
                            .addComponent(t_nope, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(jLabel4)
                            .addGap(279, 279, 279)
                            .addComponent(jLabel3))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(100, 100, 100)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(16, 16, 16)
                            .addComponent(t_tambah)
                            .addGap(21, 21, 21)
                            .addComponent(t_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(383, 383, 383)
                            .addComponent(jLabel7))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(193, 193, 193)
                            .addComponent(t_tempat, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(546, 546, 546)
                            .addComponent(t_wali, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(193, 193, 193)
                            .addComponent(t_noinduk, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(546, 546, 546)
                            .addComponent(t_cbtarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(jLabel2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(193, 193, 193)
                            .addComponent(t_cblaki))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(546, 546, 546)
                            .addComponent(t_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(292, 292, 292)
                            .addComponent(jButton1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(395, 395, 395)
                            .addComponent(t_hapus))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(282, 282, 282)
                            .addComponent(t_cbpr))
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(81, 81, 81)
                            .addComponent(jLabel6)
                            .addGap(22, 22, 22)
                            .addComponent(t_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(14, 14, 14)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(t_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(t_nope, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel8))))
                            .addGap(2, 2, 2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(7, 7, 7)
                                    .addComponent(jLabel4))
                                .addComponent(jLabel3))
                            .addGap(99, 99, 99)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton2)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(t_tambah)
                                        .addComponent(t_edit)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(121, 121, 121)
                            .addComponent(jLabel7))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(157, 157, 157)
                            .addComponent(t_tempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(119, 119, 119)
                            .addComponent(t_wali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(75, 75, 75)
                            .addComponent(t_noinduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(81, 81, 81)
                            .addComponent(t_cbtarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(77, 77, 77)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(119, 119, 119)
                            .addComponent(jLabel2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(195, 195, 195)
                            .addComponent(t_cblaki))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(188, 188, 188)
                            .addComponent(t_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(69, 69, 69)
                            .addComponent(jButton1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(314, 314, 314)
                            .addComponent(t_hapus))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(195, 195, 195)
                            .addComponent(t_cbpr))
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_tambahActionPerformed
        // TODO add your handling code here:
        if ((t_noinduk.getText().equals(""))) {
            JOptionPane.showMessageDialog(this, "Isi Data dengan Lengkap!");
        } else {
            try {
                String JenKel;
                if (t_cblaki.isSelected()) {
                    JenKel = "Laki-Laki";
                } else {
                    JenKel = "Perempuan";
                }
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String Tanggal = String.valueOf(sdf.format(t_tanggal.getDate()));

                String sql = "insert into pdb values (?,?,?,?,?,?,?,?,?)";
                Class.forName("com.mysql.jdbc.Driver");
                Connection koneksi = DriverManager.getConnection("jdbc:mysql:///skripsi", "root", "");
                PreparedStatement tulis = koneksi.prepareStatement(sql);
                tulis.setString(1, t_noinduk.getText());
                tulis.setString(2, t_nama.getText());
                tulis.setString(3, t_tempat.getText());
                tulis.setString(4, Tanggal);
                tulis.setString(5, JenKel);
                tulis.setString(6, t_cbtarget.getSelectedItem().toString());
                tulis.setString(7, t_wali.getText());
                tulis.setString(8, t_nope.getText());
                tulis.setString(9, t_alamat.getText());
                tulis.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Berhasil Di Simpan");
                bersih();
                autokode3();
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, ex);
                //Logger.getLogger(form_datatahfidz.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);
                //Logger.getLogger(form_datatahfidz.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_t_tambahActionPerformed

    private void t_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_editActionPerformed
        // TODO add your handling code here:

        if ((t_noinduk.getText().equals(""))) {
            JOptionPane.showMessageDialog(this, "Isi Data dengan Lengkap!");
        } else {
            try {
                String JenKel;
                if (t_cblaki.isSelected()) {
                    JenKel = "Laki-Laki";
                } else {
                    JenKel = "Perempuan";
                }
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String Tanggal = String.valueOf(sdf.format(t_tanggal.getDate()));

                String sql = "UPDATE peserta_tahfidz SET nama=?,tempat_lahir=?,"
                        + "tanggal_lahir=?,jenkel=?,targethafalan=?,wali/ortu=?,nope=?,Alamat=?"
                        + " WHERE no_induk=?";
                Class.forName("com.mysql.jdbc.Driver");
                Connection koneksi = DriverManager.getConnection("jdbc:mysql:///skripsi", "root", "");
                PreparedStatement tulis = koneksi.prepareStatement(sql);
                tulis.setString(9, t_noinduk.getText());
                tulis.setString(1, t_nama.getText());
                tulis.setString(2, t_tempat.getText());
                tulis.setString(3, Tanggal);
                tulis.setString(4, JenKel);
                tulis.setString(5, t_cbtarget.getSelectedItem().toString());
                tulis.setString(6, t_wali.getText());
                tulis.setString(7, t_nope.getText());
                tulis.setString(8, t_alamat.getText());
                tulis.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Berhasil Di Diedit");
                bersih();
                autokode3();
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, ex);
                //Logger.getLogger(form_datatahfidz.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);
                //Logger.getLogger(form_datatahfidz.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_t_editActionPerformed

    private void t_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_hapusActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "Delete from peserta_tahfidz where no_pendaftar=?";
            Class.forName("com.mysql.jdbc.Driver");
            Connection koneksi = DriverManager.getConnection("jdbc:mysql:///skripsi", "root", "");
            PreparedStatement tulis = koneksi.prepareStatement(sql);
            tulis.setString(1, t_noinduk.getText());
            tulis.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Berhasil Di Hapus ");
            bersih();
            //refresh();
            //Tampil_Tabel();
            //input();
            autokode3();
        } catch (ClassNotFoundException | SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(this, e);
        }

    }//GEN-LAST:event_t_hapusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        t_noinduk.setEnabled(true);
        t_edit.setEnabled(true);
        t_hapus.setEnabled(true);
        t_tambah.setEnabled(false);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        bersih();
        autokode3();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void t_noindukKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_noindukKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            //String Tanggal = String.valueOf(sdf.format(J_date.getDate()));
            Date dateValue = null;
            try {
                String query = "SELECT * FROM peserta_tahfidz WHERE no_induk = '" + t_noinduk.getText() + "'";
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(query);

                while (rs.next()) {

                    String np = rs.getString("no_induk");
                    String nama = rs.getString("nama");
                    String jengkeldb = rs.getString("jenkel");
                    String tempat_lahirdb = rs.getString("tempat_lahir");
                    String tanggal_lahirdb = rs.getString("tanggal_lahir");
                    String pendidikandb = rs.getString("pendidikan");
                    String masuk_lembagadb = rs.getString("masuk_lembaga");
                    String anak_kedb = rs.getString("anak_ke");
                    String daridb = rs.getString("dari");
                    String status_anakdb = rs.getString("status_anak");
                    String nama_ayahdb = rs.getString("nama_ayah");
                    String nama_ibudb = rs.getString("nama_ibu");
                    String alamatdb = rs.getString("alamat");
                    String penghasilan_ortudb = rs.getString("penghasilan_ortu");
                    String pendidikan_ayahdb = rs.getString("pendidikan_ayah");
                    String pendidikan_ibudb = rs.getString("pendidikan_ibu");
                    String no_hpdb = rs.getString("no_hp");
                    String administrasidb = rs.getString("administrasi");
                    String fotodb = rs.getString("foto");
                    String ijazahdb = rs.getString("ijazah");
                    String targetdb = rs.getString("target_hafalan");

                    t_noinduk.setText(np);
                    t_nama.setText(nama);
                    t_tempat.setText(tempat_lahirdb);
                    dateValue = sdf.parse(tanggal_lahirdb);
                    t_tanggal.setDate(dateValue);
                    t_cbtarget.setSelectedItem(targetdb);
                    t_wali.setText(nama_ayahdb);
                    t_nope.setText(no_hpdb);
                    t_alamat.setText(alamatdb);

                    if (jengkeldb.equals("Laki-Laki")) {
                        t_cblaki.setSelected(true);
                        t_cbpr.setSelected(false);
                    } else {
                        t_cbpr.setSelected(true);
                        t_cblaki.setSelected(false);
                    }

                }
            } catch (SQLException | ParseException e) {
                JOptionPane.showMessageDialog(this, e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Tidak ditekan Enter");
        }
    }//GEN-LAST:event_t_noindukKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jdialog_datatahfidz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jdialog_datatahfidz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jdialog_datatahfidz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jdialog_datatahfidz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Jdialog_datatahfidz dialog = new Jdialog_datatahfidz(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void autokode3() {
        try {
            String query = "SELECT MAX(right(no_induk,1))AS no FROM peserta_tahfidz";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                if (rs.first() == false) {
                    t_noinduk.setText("1711001");
                } else {
                    rs.last();
                    int auto_id = rs.getInt(1) + 1;
                    String no = String.valueOf(auto_id);
                    int nolong = no.length();
                    for (int a = 0; a < 1 - nolong; a++) {
                        no = "171100" + no;
                    }
                    t_noinduk.setText("171100" + no);
                }
            }
            rs.close();
            st.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR:\n" + e.toString(), "kesalahan", JOptionPane.WARNING_MESSAGE);
        }
    }

    public void bersih() {
        t_noinduk.setText(null);
        t_nama.setText(null);
        t_cblaki.setSelected(false);
        t_cbpr.setSelected(false);
        t_tempat.setText(null);
        t_tanggal.setDate(null);
        t_cbtarget.setSelectedItem(null);
        t_wali.setText(null);
        t_nope.setText(null);
        t_alamat.setText(null);
        t_cblaki.setSelected(false);
        t_cbpr.setSelected(false);
        t_noinduk.setEnabled(false);
        t_edit.setEnabled(false);
        t_hapus.setEnabled(false);
        t_tambah.setEnabled(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField t_alamat;
    private javax.swing.JRadioButton t_cblaki;
    private javax.swing.JRadioButton t_cbpr;
    private javax.swing.JComboBox t_cbtarget;
    private javax.swing.JButton t_edit;
    private javax.swing.JButton t_hapus;
    private javax.swing.JTextField t_nama;
    private javax.swing.JTextField t_noinduk;
    private javax.swing.JTextField t_nope;
    private javax.swing.JButton t_tambah;
    private com.toedter.calendar.JDateChooser t_tanggal;
    private javax.swing.JTextField t_tempat;
    private javax.swing.JTextField t_wali;
    // End of variables declaration//GEN-END:variables
}
